/*
 * Corporation API
 *
 * Corporation API定義
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

// CorporationCreate - 企業情報登録
type CorporationCreate struct {

	// 企業名
	Name string `json:"name"`

	// 企業ドメイン
	Domain string `json:"domain"`

	// 企業番号
	Number int32 `json:"number"`

	// 企業種別
	CorpType string `json:"corp_type"`
}
