/*
 * Corporation API
 *
 * Corporation API定義
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

// ErrorErrorInfo - 詳細
type ErrorErrorInfo struct {

	// エラーメッセージ
	Message string `json:"message,omitempty"`
}
