/*
 * Corporation API
 *
 * Corporation API定義
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

// CorporationPatch - 企業情報更新
type CorporationPatch struct {

	// 企業名
	Name string `json:"name"`

	// 企業ドメイン
	Domain *string `json:"domain,omitempty"`

	// 企業番号
	Number *int32 `json:"number,omitempty"`

	// 企業種別
	CorpType string `json:"corp_type"`
}
