/*
 * Corporation API
 *
 * Corporation API定義
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

// CorporationCreate - 企業情報登録
type CorporationCreate struct {

	// 企業ID
	CorporationId *string `json:"corporation_id,omitempty"`

	// 企業名
	Name *string `json:"name,omitempty"`

	// 企業ドメイン
	Domain *string `json:"domain,omitempty"`

	// 企業番号
	Number *int32 `json:"number,omitempty"`

	// 企業種別
	CorpType *string `json:"corp_type,omitempty"`
}
