/*
 * Corporation API
 *
 * Corporation API定義
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

type ModelError struct {

	// エラーコード
	Code int32 `json:"code,omitempty"`

	// エラータイプ
	Type string `json:"type,omitempty"`

	// エラーメッセージ
	Message string `json:"message,omitempty"`
}
